### ISSUE TITLE
Confused about pseudo-elements in 5.0

### ISSUE THREAD

**Issue by jessephillips** [FortAwesome/font-awesome-sass#159]
I was confused about how to use FontAwesome icons in 5.0. I eventually figured it out, but I think this (or something like it) would be a helpful addition to the docs (note: this is my first time ever making a suggested change to a public repo. I apologize if this is foolish or rude or something).

My suggested change to README.md:

#### CSS Pseudo Element Usage (:before/:after)
(See FontAwesome docs for more details on [pseudo-elements](https://fontawesome.com/how-to-use/on-the-web/advanced/css-pseudo-elements))

4.x Syntax

```css
&:before {
  font-family: "FontAwesome";
  content: "\f058"; // check-circle
}
```

5.x Syntax
  * The font-family is `Font Awesome 5 Free`
  * Use `font-weight: 900` for solid icons

```css
&:before {
  font-family: "Font Awesome 5 Free";
  font-weight: 900;
  content: "\f058";
}
```
