### ISSUE TITLE
Font files don't get copied from gem

### ISSUE THREAD

**Issue by olavk** [FortAwesome/font-awesome-sass#45]
I am using font-awesome-sass with Compass, without Rails. The .css gets copied into css/font-awesome/font-awesome.css but there are no font-awesome fonts in my fonts directory.

I've done:
gem install compass
gem install bootstrap-sass
gem install font-awesome-sass

config.rb:

require 'bootstrap-sass'
require 'compass/import-once/activate'
require 'font-awesome-sass'
http_path = "/"
css_dir = "css"
sass_dir = "sass"
images_dir = "images"
javascripts_dir = "js"
fonts_dir = "fonts"
relative_assets = true

styles.scss:

@import "bootstrap-compass";
@import "bootstrap-variables";
@import "bootstrap";
@import "font-awesome-compass";
@import "font-awesome";

Fonts directory only has glyphicons from bootstrap-sass, and it works, so i know the paths are correct. Only font-awesome doesn't get fonts copied

**Comment by kumiau** [comment]
Same here. Running a compass only project. My processed css is generating the url with the function "font-path": 

```css
@font-face {
  font-family: 'FontAwesome';
  src: url(font-path("font-awesome/fontawesome-webfont.eot"));
  src: url(font-path("font-awesome/fontawesome-webfont.eot?#iefix")) format("embedded-opentype"), url(font-path("font-awesome/fontawesome-webfont.woff2")) format("woff2"), url(font-path("font-awesome/fontawesome-webfont.woff")) format("woff"), url(font-path("font-awesome/fontawesome-webfont.ttf")) format("truetype"), url(font-path("font-awesome/fontawesome-webfont.svg#fontawesomeregular")) format("svg");
  font-weight: normal;
  font-style: normal;
}
```
