### ISSUE TITLE
Using SASS maps for storing settings

### ISSUE THREAD

**Issue by GEEKIAM** [FortAwesome/font-awesome-sass#69]
Hi there!
What do you think about this?

It will be looks something like this:
```Sass
$fa-settings: (
  font-path: f($fa-sass-asset-helper, "font-awesome/", "../fonts/font-awesome/"),
  css-prefix: "fa",
  icons-map: (
    adjust: "\f042",
    adn: "\f170"
  )
) !default; 
```

and with SASS maps we can do it this:
```Sass
@each $icon-name, $icon-code in map-get($fa-settings, icons-map) {
  .#{map-get($fa-settings, css-prefix)}-#{$icon-name}::before {
    content: $icon-code;
  }
}
```

It's awesome, isn't it? :sunglasses:

**Comment by ksubileau** [comment]
:+1:

I need to `@extend` all the default fa-* icons classes in order to add the icon on a child element instead of the element itself. This is what I'm doing currently:
```scss
$fa-icons: glass music search envelope-o heart //[...]
@each $name in $fa-icons {
    // Apply icon on the child link instead of on the li element
    li.nav-ic-#{$name} > a {
        @extend .#{$fa-css-prefix}-#{$name}
    }
}
```
I had to manually define the icons list (`$fa-icons`) to be able to use a loop. It would be better if this list was defined directly inside Font Awesome !
